// Copyright 2026 aki-riko
// SPDX-License-Identifier: MIT
// This file is part of FluentQML, licensed under MIT.

import QtQuick
import "../../.."
import "../../icons"
import "../../containers"
import "../../data"

// SettingsCardCore - Setting card container 设置卡片容器
// Pure container mode: user adds widgets via addRightWidget() 纯容器模式：用户通过addRightWidget()添加控件
// Design principle: Composition over Inheritance 设计理念：组合优于继承
Card {
    id: control
    cardType: Enums.card.type_default
    borderRadius: Enums.radius.card
    
    // ==================== Public Props 公开属性 ====================
    property string icon: ""           // Icon name or image path 图标
    property alias title: titleLabel.text   // Title text 标题
    property alias content: contentLabel.text  // Description text 描述
    property bool disabled: false      // Disabled state 禁用状态
    
    // ==================== Expandable Props 可展开属性 ====================
    property bool expandable: false    // Whether card is expandable 是否可展开
    property bool expanded: false      // Current expanded state 当前展开状态
    // Note: expandedChanged signal is auto-generated by QML for 'expanded' property 注意：QML 会自动为 expanded 属性生成 expandedChanged 信号
    
    // ==================== Content Area 内容区域 ====================
    default property alias contentItem: contentArea.data
    
    // ==================== Public Methods 公开方法 ====================
    // Add widget to right area (for Python: card.addWidget(toggle)) 添加控件到右侧区域
    function addRightWidget(widget) {
        widget.parent = contentArea
    }
    
    // Add widget to expand area (for Python: card.addExpandContent(widget)) 添加控件到展开区域
    function addExpandWidget(widget) {
        expandable = true
        widget.parent = expandContent
    }
    
    // ==================== Size 尺寸 ====================
    implicitWidth: Enums.controlSize.cardWidth
    implicitHeight: mainRow.implicitHeight + (expandable && expanded ? expandArea.height : 0)
    
    // ==================== Opacity 透明度 ====================
    opacity: disabled ? Enums.opacityLevel.disabled : Enums.opacityLevel.visible
    
    // ==================== Expand State Change 展开状态变化 ====================
    // Property change signal is auto-generated, no need to emit manually
    
    // ==================== Main Layout 主布局 ====================
    Column {
        anchors.fill: parent
        spacing: 0
        
        // Main row 主行
        Row {
            id: mainRow
            width: parent.width
            height: contentLabel.text !== "" ? Enums.settingCard.height_with_content : Enums.settingCard.height_no_content
            leftPadding: Enums.spacing.xl
            rightPadding: Enums.spacing.xl
            spacing: Enums.spacing.none
            
            // Icon 图标 (16x16)
            Item {
                width: control.icon !== "" ? (Enums.settingCard.icon_size + Enums.spacing.xl) : 0
                height: parent.height
                visible: control.icon !== ""
                
                Icon {
                    id: iconItem
                    anchors.left: parent.left
                    anchors.verticalCenter: parent.verticalCenter
                    iconSize: Enums.settingCard.icon_size
                    icon: control.icon
                    color: Enums.textColor.primary
                    opacity: control.disabled ? Enums.opacityLevel.disabled : Enums.opacityLevel.visible
                }
            }
            
            // Title and content 标题和内容
            Column {
                anchors.verticalCenter: parent.verticalCenter
                spacing: Enums.spacing.none
                width: parent.width - parent.leftPadding - parent.rightPadding 
                       - (control.icon !== "" ? (Enums.settingCard.icon_size + Enums.spacing.xl) : 0) 
                       - contentArea.width - Enums.spacing.xl
                       - (control.expandable ? expandButton.width + Enums.spacing.sm : 0)
                
                Label {
                    id: titleLabel
                    type: Enums.label.type_body_strong
                    width: parent.width
                    elide: Text.ElideRight
                }
                
                Label {
                    id: contentLabel
                    type: Enums.label.type_caption
                    color: Enums.stateColor.settingCardContent
                    visible: text !== ""
                    width: parent.width
                    elide: Text.ElideRight
                }
            }
            
            // Spacer 占位
            Item { 
                width: Enums.spacing.xl
                height: 1
            }
            
            // Custom content area 自定义内容区域 (右侧)
            Row {
                id: contentArea
                anchors.verticalCenter: parent.verticalCenter
                spacing: Enums.spacing.s
            }
            
            // Expand button 展开按钮
            Item {
                width: control.expandable ? expandButton.width + Enums.spacing.s : 0
                height: parent.height
                visible: control.expandable
                
                Icon {
                    id: expandButton
                    anchors.right: parent.right
                    anchors.verticalCenter: parent.verticalCenter
                    icon: "ChevronDown"
                    iconSize: 12
                    color: Enums.textColor.secondary
                    rotation: control.expanded ? 180 : 0
                    Behavior on rotation { NumberAnimation { duration: Enums.duration.medium } }  // 150
                    
                    MouseArea {
                        anchors.fill: parent
                        anchors.margins: -8
                        cursorShape: Qt.PointingHandCursor
                        onClicked: control.expanded = !control.expanded
                    }
                }
            }
        }
        
        // Expand area 展开区域
        Item {
            id: expandArea
            width: parent.width
            height: control.expandable && control.expanded ? expandContent.height + Enums.spacing.lg : 0
            clip: true
            visible: control.expandable
            
            Behavior on height { NumberAnimation { duration: Enums.duration.medium; easing.type: Easing.OutCubic } }  // 200
            
            // Separator 分隔线
            Separator {
                width: parent.width - Enums.spacing.xl * 2
                anchors.horizontalCenter: parent.horizontalCenter
                anchors.top: parent.top
                visible: control.expanded
            }
            
            // Expand content container 展开内容容器
            Column {
                id: expandContent
                anchors.top: parent.top
                anchors.topMargin: Enums.spacing.m
                anchors.left: parent.left
                anchors.right: parent.right
                anchors.leftMargin: Enums.spacing.xl
                anchors.rightMargin: Enums.spacing.xl
                spacing: Enums.spacing.s
            }
        }
    }
}
