# coding: utf-8
# SPDX-License-Identifier: MIT
# This file is part of PrismQML, licensed under MIT.
# 本文件是 PrismQML 的一部分，采用 MIT 许可证授权。
"""Windows installer manifest and CLI contracts. Windows 安装器清单与 CLI 合同。"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

from prismqml.python.tools import _windows_installer_compile as installer_compile
from prismqml.python.tools.windows_installer import (
    EXIT_COMPILE,
    EXIT_MANIFEST,
    EXIT_OK,
    EXIT_STALE_OUTPUT,
    ManifestError,
    build_parser,
    check_installer,
    doctor_manifest,
    generate_installer,
    load_manifest,
    main,
    render_installer,
)


ROOT = Path(__file__).resolve().parents[1]
MODULE = "prismqml.python.tools.windows_installer"


def _manifest_data(**overrides):
    data = {
        "schema": 1,
        "app_id": "8F3A9C2E-5B1D-4E7A-9C6F-A1B2C3D4E5F6",
        "name": "ExampleApp",
        "publisher": "Aquila",
        "executable": "ExampleApp.exe",
        "aumid": "PrismQML.ExampleApp",
        "install_scope": "user",
        "dist_dir": "build/main.dist",
    }
    data.update(overrides)
    return data


def _write_manifest(tmp_path: Path, **overrides) -> Path:
    path = tmp_path / "prismqml-installer.json"
    path.write_text(
        json.dumps(_manifest_data(**overrides), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return path


def test_minimal_manifest_renders_silent_next_launch_contract(tmp_path):
    manifest_path = _write_manifest(tmp_path)
    manifest = load_manifest(manifest_path)
    output_path = tmp_path / "installer.generated.iss"

    rendered = render_installer(manifest, output_path, "1.2.3.4")

    assert "; Generated by prismqml-installer. DO NOT EDIT." in rendered
    assert "AppId={{8F3A9C2E-5B1D-4E7A-9C6F-A1B2C3D4E5F6}" in rendered
    assert "AppVersion={#PrismAppVersion}" in rendered
    assert "DefaultDirName={localappdata}\\Programs\\{#PrismAppName}" in rendered
    assert "PrivilegesRequired=lowest" in rendered
    assert "CloseApplications=yes" in rendered
    assert "RestartApplications=no" in rendered
    assert "Flags: nowait postinstall skipifsilent" in rendered
    assert "/RESTARTAPPLICATIONS" not in rendered
    assert "/AUTORESTARTAPP" not in rendered
    assert str(tmp_path) not in rendered


def test_machine_manifest_and_optional_sections_are_rendered_relatively(tmp_path):
    (tmp_path / "installer").mkdir()
    manifest_path = _write_manifest(
        tmp_path,
        install_scope="machine",
        homepage="https://example.test/example-app",
        icon="assets/app.ico",
        extension_include="installer/legacy.issinc",
        installer_output_dir="release/setup",
        output_name="ExampleApp_Setup_{version}",
    )
    output_path = tmp_path / "generated" / "installer.iss"
    manifest = load_manifest(manifest_path)

    rendered = render_installer(manifest, output_path, "2.0.0")

    assert "DefaultDirName={autopf}\\{#PrismAppName}" in rendered
    assert "PrivilegesRequired=admin" in rendered
    assert '#define PrismAppURL "https://example.test/example-app"' in rendered
    assert '#define PrismSetupIcon "..\\assets\\app.ico"' in rendered
    assert '#define PrismDistDir "..\\build\\main.dist"' in rendered
    assert "OutputDir=..\\release\\setup" in rendered
    assert "OutputBaseFilename=ExampleApp_Setup_2.0.0" in rendered
    assert '#include "..\\installer\\legacy.issinc"' in rendered
    assert str(tmp_path) not in rendered


@pytest.mark.parametrize(
    ("overrides", "match"),
    [
        ({"schema": 2}, "schema"),
        ({"unknown_option": True}, "unknown"),
        ({"install_scope": "portable"}, "install_scope"),
        ({"executable": "bin/ExampleApp.exe"}, "executable"),
        ({"dist_dir": "../outside"}, "dist_dir"),
        ({"homepage": "http://example.test/app"}, "homepage"),
    ],
)
def test_manifest_rejects_ambiguous_or_unsafe_values(tmp_path, overrides, match):
    manifest_path = _write_manifest(tmp_path, **overrides)

    with pytest.raises(ManifestError, match=match):
        load_manifest(manifest_path)


@pytest.mark.parametrize(
    ("overrides", "match"),
    [
        ({"app_id": "not-a-guid"}, "app_id"),
        ({"dist_dir": "build/main.dist:stream"}, "dist_dir"),
        ({"icon": "assets/app?.ico"}, "icon"),
        ({"output_name": "{name.__class__}-{version}"}, "output_name"),
        ({"output_name": "ExampleApp-Setup.exe"}, "output_name"),
    ],
)
def test_manifest_rejects_values_that_cannot_form_a_portable_iss(
    tmp_path, overrides, match
):
    manifest_path = _write_manifest(tmp_path, **overrides)

    with pytest.raises(ManifestError, match=match):
        load_manifest(manifest_path)


def test_render_rejects_invalid_release_version(tmp_path):
    manifest = load_manifest(_write_manifest(tmp_path))

    with pytest.raises(ManifestError, match="version"):
        render_installer(manifest, tmp_path / "installer.iss", "latest")


def test_generate_is_atomic_and_does_not_rewrite_identical_output(tmp_path):
    manifest_path = _write_manifest(tmp_path)
    manifest = load_manifest(manifest_path)
    output_path = tmp_path / "installer.generated.iss"

    first = generate_installer(manifest, output_path, "1.0.0")
    first_timestamp = output_path.stat().st_mtime_ns
    second = generate_installer(manifest, output_path, "1.0.0")

    assert first.changed is True
    assert second.changed is False
    assert first.sha256 == second.sha256
    assert output_path.stat().st_mtime_ns == first_timestamp
    assert check_installer(manifest, output_path, "1.0.0").sha256 == first.sha256


def test_generate_replaces_non_utf8_generated_output(tmp_path):
    manifest = load_manifest(_write_manifest(tmp_path))
    output_path = tmp_path / "installer.generated.iss"
    output_path.write_bytes(b"\xff\xfe stale")

    result = generate_installer(manifest, output_path, "1.0.0")

    assert result.changed is True
    assert output_path.read_text(encoding="utf-8").startswith(
        "; SPDX-License-Identifier: MIT"
    )


def test_check_reports_missing_and_stale_outputs(tmp_path):
    manifest = load_manifest(_write_manifest(tmp_path))
    output_path = tmp_path / "installer.generated.iss"

    with pytest.raises(ManifestError, match="missing") as missing:
        check_installer(manifest, output_path, "1.0.0")
    assert missing.value.exit_code == EXIT_STALE_OUTPUT

    output_path.write_text("stale\n", encoding="utf-8")
    with pytest.raises(ManifestError, match="stale") as stale:
        check_installer(manifest, output_path, "1.0.0")
    assert stale.value.exit_code == EXIT_STALE_OUTPUT


def test_json_cli_has_stable_generate_check_and_error_shapes(tmp_path, capsys):
    manifest_path = _write_manifest(tmp_path)
    output_path = tmp_path / "installer.generated.iss"
    common = [
        "--json",
        "--manifest",
        str(manifest_path),
        "--version",
        "1.0.0",
        "--output",
        str(output_path),
    ]

    assert main(["generate", *common]) == EXIT_OK
    generated = json.loads(capsys.readouterr().out)
    assert generated["ok"] is True
    assert generated["command"] == "generate"
    assert generated["changed"] is True
    assert generated["output"] == str(output_path.resolve())

    assert main(["check", *common]) == EXIT_OK
    checked = json.loads(capsys.readouterr().out)
    assert checked["ok"] is True
    assert checked["command"] == "check"

    output_path.write_text("stale\n", encoding="utf-8")
    assert main(["check", *common]) == EXIT_STALE_OUTPUT
    failed = json.loads(capsys.readouterr().out)
    assert failed == {
        "ok": False,
        "command": "check",
        "error": {
            "code": "stale_output",
            "message": f"generated installer is stale: {output_path.resolve()}",
        },
    }


def test_doctor_reports_missing_build_inputs_without_failing(tmp_path, capsys):
    manifest_path = _write_manifest(tmp_path, icon="assets/app.ico")

    assert main([
        "doctor", "--json", "--manifest", str(manifest_path)
    ]) == EXIT_OK
    payload = json.loads(capsys.readouterr().out)

    assert payload["ok"] is True
    assert payload["command"] == "doctor"
    assert payload["ready_to_compile"] is False
    assert payload["checks"]["dist_dir"]["available"] is False
    assert payload["checks"]["executable"]["available"] is False
    assert payload["checks"]["icon"]["available"] is False
    assert "iscc" in payload["checks"]


def test_doctor_distinguishes_required_files_from_directories(
    tmp_path, monkeypatch
):
    dist_dir = tmp_path / "build" / "main.dist"
    executable = dist_dir / "ExampleApp.exe"
    icon = tmp_path / "assets" / "app.ico"
    executable.mkdir(parents=True)
    icon.mkdir(parents=True)
    iscc = tmp_path / "tools" / "ISCC.exe"
    iscc.parent.mkdir()
    iscc.write_bytes(b"")
    monkeypatch.setenv("PRISMQML_ISCC", str(iscc))
    manifest = load_manifest(_write_manifest(tmp_path, icon="assets/app.ico"))

    payload = doctor_manifest(manifest)

    assert payload["checks"]["dist_dir"]["available"] is True
    assert payload["checks"]["executable"]["available"] is False
    assert payload["checks"]["icon"]["available"] is False
    assert payload["checks"]["iscc"]["available"] is True
    assert payload["ready_to_compile"] is False


def _write_compile_inputs(tmp_path: Path, monkeypatch):
    dist_dir = tmp_path / "build" / "main.dist"
    dist_dir.mkdir(parents=True)
    (dist_dir / "ExampleApp.exe").write_bytes(b"app")
    iscc = tmp_path / "tools" / "ISCC.exe"
    iscc.parent.mkdir()
    iscc.write_bytes(b"compiler")
    monkeypatch.setenv("PRISMQML_ISCC", str(iscc))
    return _write_manifest(tmp_path), iscc


def test_compile_dry_run_is_read_only_and_reports_exact_command(
    tmp_path, monkeypatch, capsys
):
    manifest_path, iscc = _write_compile_inputs(tmp_path, monkeypatch)
    output_path = tmp_path / "generated" / "installer.iss"

    exit_code = main([
        "--json", "compile", "--manifest", str(manifest_path),
        "--version", "1.0.0", "--output", str(output_path), "--dry-run",
    ])
    payload = json.loads(capsys.readouterr().out)

    assert exit_code == EXIT_OK
    assert payload["command"] == "compile"
    assert payload["dry_run"] is True
    assert payload["compiled"] is False
    assert payload["argv"] == [str(iscc.resolve()), str(output_path.resolve())]
    assert payload["installer"] == str(
        (tmp_path / "dist_installer" / "ExampleApp-Setup-1.0.0.exe").resolve()
    )
    assert not output_path.exists()


def test_compile_generates_iss_and_verifies_compiler_artifact(
    tmp_path, monkeypatch, capsys
):
    manifest_path, iscc = _write_compile_inputs(tmp_path, monkeypatch)
    output_path = tmp_path / "generated" / "installer.iss"
    installer_path = tmp_path / "dist_installer" / "ExampleApp-Setup-1.0.0.exe"
    calls = []

    def fake_run(argv, **kwargs):
        calls.append((argv, kwargs))
        installer_path.parent.mkdir()
        installer_path.write_bytes(b"setup")
        return SimpleNamespace(returncode=0, stdout="compiled", stderr="")

    monkeypatch.setattr(installer_compile.subprocess, "run", fake_run)

    exit_code = main([
        "--json", "compile", "--manifest", str(manifest_path),
        "--version", "1.0.0", "--output", str(output_path),
    ])
    payload = json.loads(capsys.readouterr().out)

    assert exit_code == EXIT_OK
    assert payload["compiled"] is True
    assert payload["installer"] == str(installer_path.resolve())
    assert output_path.is_file() and installer_path.is_file()
    assert calls == [([str(iscc.resolve()), str(output_path.resolve())], {
        "capture_output": True,
        "check": False,
        "cwd": output_path.parent.resolve(),
        "encoding": "utf-8",
        "errors": "replace",
        "text": True,
    })]


def test_compile_failure_uses_stable_json_and_exit_code(
    tmp_path, monkeypatch, capsys
):
    manifest_path, _iscc = _write_compile_inputs(tmp_path, monkeypatch)
    monkeypatch.setattr(
        installer_compile.subprocess,
        "run",
        lambda *_args, **_kwargs: SimpleNamespace(
            returncode=2, stdout="", stderr="compile failed"
        ),
    )

    exit_code = main([
        "--json", "compile", "--manifest", str(manifest_path),
        "--version", "1.0.0",
    ])
    payload = json.loads(capsys.readouterr().out)

    assert exit_code == EXIT_COMPILE
    assert payload["ok"] is False
    assert payload["command"] == "compile"
    assert payload["error"]["code"] == "compile_failed"


def test_compile_zero_exit_without_expected_artifact_is_failure(
    tmp_path, monkeypatch, capsys
):
    manifest_path, _iscc = _write_compile_inputs(tmp_path, monkeypatch)
    monkeypatch.setattr(
        installer_compile.subprocess,
        "run",
        lambda *_args, **_kwargs: SimpleNamespace(
            returncode=0, stdout="compiled", stderr=""
        ),
    )

    exit_code = main([
        "--json", "compile", "--manifest", str(manifest_path),
        "--version", "1.0.0",
    ])
    payload = json.loads(capsys.readouterr().out)

    assert exit_code == EXIT_COMPILE
    assert payload["error"]["code"] == "compile_failed"
    assert "did not create expected installer" in payload["error"]["message"]


def test_compile_dry_run_reports_missing_prerequisites_without_writing(
    tmp_path, capsys
):
    manifest_path = _write_manifest(tmp_path)
    output_path = tmp_path / "installer.generated.iss"

    exit_code = main([
        "--json", "compile", "--manifest", str(manifest_path),
        "--version", "1.0.0", "--output", str(output_path), "--dry-run",
    ])
    payload = json.loads(capsys.readouterr().out)

    assert exit_code == EXIT_COMPILE
    assert payload["error"]["code"] == "compile_not_ready"
    assert not output_path.exists()


def test_cli_reports_invalid_manifest_as_machine_readable_error(tmp_path, capsys):
    manifest_path = _write_manifest(tmp_path, install_scope="invalid")

    assert main([
        "doctor", "--json", "--manifest", str(manifest_path)
    ]) == EXIT_MANIFEST
    payload = json.loads(capsys.readouterr().out)

    assert payload["ok"] is False
    assert payload["command"] == "doctor"
    assert payload["error"]["code"] == "invalid_manifest"
    assert "install_scope" in payload["error"]["message"]


def test_help_and_module_entrypoint_work_from_another_directory(tmp_path):
    help_text = build_parser().format_help()
    assert "doctor" in help_text
    assert "generate" in help_text
    assert "check" in help_text
    assert "compile" in help_text
    manifest_path = _write_manifest(tmp_path)
    environment = os.environ.copy()
    environment["PYTHONPATH"] = str(ROOT)

    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            MODULE,
            "doctor",
            "--json",
            "--manifest",
            str(manifest_path),
        ],
        cwd=tmp_path,
        env=environment,
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        check=False,
    )

    assert completed.returncode == EXIT_OK
    assert json.loads(completed.stdout)["command"] == "doctor"
    assert completed.stderr == ""


def test_json_option_is_supported_before_or_after_subcommand(tmp_path, capsys):
    manifest_path = _write_manifest(tmp_path)

    for arguments in (
        ["--json", "doctor", "--manifest", str(manifest_path)],
        ["doctor", "--json", "--manifest", str(manifest_path)],
    ):
        assert main(arguments) == EXIT_OK
        assert json.loads(capsys.readouterr().out)["command"] == "doctor"


def test_distribution_registers_cli_template_and_documentation():
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    mkdocs = (ROOT / "mkdocs.yml").read_text(encoding="utf-8")
    documentation = ROOT / "docs" / "windows-installer.md"
    english_documentation = ROOT / "docs" / "windows-installer.en.md"
    example = ROOT / "docs" / "examples" / "prismqml-installer.json"

    assert '[project.scripts]' in pyproject
    assert (
        'prismqml-installer = "prismqml.python.tools.windows_installer:main"'
        in pyproject
    )
    assert 'python/tools/templates/*.tmpl' in pyproject
    assert documentation.is_file()
    assert english_documentation.is_file()
    assert example.is_file()
    documentation_text = documentation.read_text(encoding="utf-8")
    assert "RestartApplications=no" in documentation_text
    assert "compile --manifest" in documentation_text
    assert "RestartApplications=no" in english_documentation.read_text(
        encoding="utf-8"
    )
    assert "Windows 安装器: windows-installer.md" in mkdocs
