// Copyright 2026 aki-riko
// SPDX-License-Identifier: MIT
// This file is part of PrismQML, licensed under MIT.

import QtQuick
import QtQuick.Effects
import "../../.."
import "../../icons"
import "../Card"
import "../../../effects"
import "../../data/Label"
import ".."

// ExpanderCore - Expander using Card base 展开器基类
Widget {
    id: control
    
    // ==================== Properties 属性 ====================
    property alias title: titleLabel.text
    property alias content: contentLabel.text  // Description text 描述文本
    property string icon: ""
    property bool expanded: false
    property bool disabled: false
    // contentArea 上下 padding (左右始终 spacing.l). 引擎统一负责 expandContent 上下间距,
    // 默认 spacing.l (12px) 符合 Microsoft Fluent Design 规范 (WinUI 3 Expander 标准).
    // 业务直接塞 GridLayout / Row / Column 等无自带 padding 容器即可上下对称, 不需要包 Item.
    // 设 0 退回旧行为 (业务自管 padding, 仅在已知内容自带 verticalCenter padding 时使用).
    property int contentPadding: Enums.spacing.l
    default property alias expandContent: contentArea.data
    
    // Header right content (between title and expand button) 头部右侧内容（标题和展开按钮之间）
    property alias headerContent: headerContentLoader.sourceComponent
    
    // ==================== Signals 信号 ====================
    signal toggled(bool expanded)
    // Note: expandedChanged signal is auto-generated by 'expanded' property 注意：expandedChanged 信号由 expanded 属性自动生成
    
    // ==================== Public Methods 公共方法 ====================
    // Get expanded state 获取展开状态
    function isExpanded() {
        return expanded
    }
    
    
    // Toggle expanded state 切换展开状态
    function toggle() {
        expanded = !expanded
        toggled(expanded)
    }
    
    
    // Expand 展开
    function expand() {
        expanded = true
    }
    
    // Collapse 收起
    function collapse() {
        expanded = false
    }
    
    // Add widget to header (right side) 添加控件到头部（右侧）
    function addHeaderWidget(widget) {
        if (headerContentLoader && headerContentLoader.item) {
            widget.parent = headerContentLoader.item
        }
    }
    
    // Add widget to expand content area 添加控件到展开内容区域
    function addExpandWidget(widget) {
        widget.parent = contentArea
        // Call hook if defined (for subclass customization)
        if (typeof onWidgetAdded === "function") {
            onWidgetAdded(widget)
        }
    }
    
    // Hook for subclass to handle widget addition 子类处理控件添加的钩子
    property var onWidgetAdded: null
    
    // ==================== Internal 内部状态 ====================
    readonly property bool hovered: !control.disabled && headerArea.containsMouse
    readonly property bool pressed: !control.disabled && headerArea.pressed
    readonly property int _radius: Enums.radius.card + 1
    
    // ==================== Size 尺寸 ====================
    // Content size (inherited from Widget, only width) 内容尺寸（继承自Widget，仅宽度）
    contentWidth: Enums.controlSize.cardWidth
    // Height is always dynamic 高度始终动态
    implicitHeight: mainContainer.height + Enums.spacing.xs
    
    // ==================== Shadow Layer 阴影层 ====================
    // Fluent: 模糊阴影; Neobrutalism: 硬阴影(NeoShadow)。
    RectangularShadow {
        anchors.fill: mainContainer
        radius: control._radius
        color: Enums.shadow.level2.color
        blur: Enums.shadow.level2.blur
        offset.x: 0
        offset.y: Enums.shadow.level2.offset
        visible: !Enums.isNeobrutalism
    }

    NeoShadow {
        target: mainContainer
        visible: Enums.isNeobrutalism
        radius: control._radius
        z: mainContainer.z - 1
    }
    
    // ==================== Main Container 主容器（无边框，只做裁剪）====================
    Item {
        id: mainContainer
        anchors.left: parent.left
        anchors.right: parent.right
        anchors.top: parent.top
        height: headerContent.height + (control.expanded ? viewContainer.height : 0)
        clip: true
        opacity: control.disabled ? Enums.opacityLevel.disabled : Enums.opacityLevel.visible
        
        // Height animation 高度动画
        Behavior on height { 
            NumberAnimation { 
                duration: Enums.duration.medium
                easing.type: Easing.OutQuad 
            } 
        }
        
        // ==================== Background 背景层 ====================
        Rectangle {
            id: bgRect
            anchors.fill: parent
            radius: control._radius
            color: Enums.stateColor.controlBg
            // neo: 粗黑边(Fluent 无边靠阴影区分; neo 需黑边)
            border.width: Enums.isNeobrutalism ? Enums.neo.borderWidth : 0
            border.color: Enums.isNeobrutalism ? Enums.stateColor.border : Enums.transparent
        }
        
        // ==================== Header Content 头部内容 ====================
        Item {
            id: headerContent
            anchors.top: parent.top
            anchors.left: parent.left
            anchors.right: parent.right
            height: contentLabel.text !== "" ? 72 : 48
            
            // ==================== Card Layout 卡片布局 ====================
            Row {
                id: headerRow
                anchors.fill: parent
                anchors.leftMargin: Enums.spacing.xl
                anchors.rightMargin: Enums.spacing.xl  // 对称, 之前 spacing.m 比左侧窄
                spacing: Enums.spacing.none
                z: Enums.zIndex.content  // Above mouse area 在鼠标区域之上
                
                // Icon 图标
                Item {
                    width: control.icon !== "" ? (Enums.iconSize.m + Enums.spacing.xl) : 0
                    height: parent.height
                    visible: control.icon !== ""
                    
                    Icon {
                        anchors.left: parent.left
                        anchors.verticalCenter: parent.verticalCenter
                        iconSize: Enums.iconSize.m
                        icon: control.icon
                        color: Enums.textColor.primary
                    }
                }
                
                // Title and content 标题和内容
                Column {
                    id: titleCol
                    anchors.verticalCenter: parent.verticalCenter
                    spacing: Enums.spacing.none
                    
                    Label {
                        id: titleLabel
                        type: Enums.label.type_body
                    }
                    
                    Label {
                        id: contentLabel
                        type: Enums.label.type_caption
                        color: Enums.stateColor.settingCardContent
                        visible: text !== ""
                    }
                }
                
                // Spacer 弹性空间
                Item { 
                    width: Math.max(1, headerContent.width - Enums.spacing.xl - Enums.spacing.m - (control.icon !== "" ? (Enums.iconSize.m + Enums.spacing.xl) : 0) - titleCol.implicitWidth - headerContentLoader.width - Enums.controlSize.expanderIconSize - (headerContentLoader.item ? Enums.spacing.xl : 0))
                    height: Enums.border.thin 
                }
                
                // Header content loader 头部内容加载器
                Loader {
                    id: headerContentLoader
                    anchors.verticalCenter: parent.verticalCenter
                }
                
                // Spacing between header content and expand button 头部内容与展开按钮之间的间距
                Item {
                    width: headerContentLoader.item ? Enums.spacing.xl : 0
                    height: Enums.border.thin
                    visible: headerContentLoader.item
                }
                
                // Expand button 展开按钮 (Fluent Design: 30x30)
                Item {
                    width: Enums.controlSize.expanderIconSize
                    height: Enums.controlSize.expanderIconSize
                    anchors.verticalCenter: parent.verticalCenter
                    
                    Rectangle {
                        anchors.fill: parent
                        radius: Enums.radius.small
                        color: {
                            if (control.pressed) return Enums.stateColor.expandBtnPressed
                            if (control.hovered) return Enums.stateColor.expandBtnHover
                            return Enums.transparent
                        }
                    }
                    
                    // Arrow icon with rotation 带旋转的箭头图标
                    Icon {
                        anchors.centerIn: parent
                        iconSize: Enums.iconSize.tiny
                        icon: Enums.icon.chevron_down
                        color: Enums.textColor.secondary
                        rotation: control.expanded ? 180 : 0
                        
                        Behavior on rotation {
                            NumberAnimation { 
                                duration: Enums.duration.medium
                                easing.type: Easing.OutQuad
                            }
                        }
                    }
                }
            }
            
            // Click handler 点击处理
            MouseArea {
                id: headerArea
                anchors.fill: parent
                hoverEnabled: true
                enabled: !control.disabled
                onClicked: { 
                    control.expanded = !control.expanded
                    control.toggled(control.expanded)
                }
            }
        }
        
        // ==================== Separator 分隔线 ====================
        Separator {
            anchors.top: headerContent.bottom
            anchors.left: parent.left
            anchors.right: parent.right
            lineColor: Enums.stateColor.expanderSeparator
            lineWidth: Enums.isNeobrutalism ? Enums.neo.borderWidth : Enums.border.thin  // neo: 粗黑分隔线
            visible: control.expanded
            // 必须高于 viewContainer, 否则 viewContainer 内 expandViewBg
            // (anchors.topMargin: -_radius 向上延伸) 会盖住 separator
            z: 1
        }
        
        // ==================== Expanded View 展开内容 ====================
        Item {
            id: viewContainer
            anchors.top: headerContent.bottom
            anchors.left: parent.left
            anchors.right: parent.right
            // contentPadding 默认 0 (兼容 SettingsCard 内层 Item 自带 padding 场景);
            // 业务装 GridLayout/Row 等无自带 padding 容器时设非 0 让上下对称
            height: control.expanded ? contentArea.implicitHeight + control.contentPadding * 2 : 0
            visible: control.expanded

            // Background with bottom radius 带底部圆角的背景
            Rectangle {
                anchors.fill: parent
                color: Enums.stateColor.expandViewBg
                // Only bottom corners rounded 只有底部圆角
                radius: control._radius
                // Clip top corners by extending above 通过向上延伸裁剪顶部圆角
                anchors.topMargin: -control._radius
                // neo: 左右下各内缩边框宽度, 露出底层 bgRect 的黑边(否则白块贴边盖住黑边,
                // 展开后底部+两侧看不到边)。不加自己的边框, 避免盒中盒。
                readonly property int _neoInset: Enums.isNeobrutalism ? Enums.neo.borderWidth : 0
                anchors.leftMargin: _neoInset
                anchors.rightMargin: _neoInset
                anchors.bottomMargin: _neoInset
            }

            // Content area 内容区域（Column 布局，子控件垂直排列）
            Column {
                id: contentArea
                objectName: "contentArea"
                anchors.left: parent.left
                anchors.right: parent.right
                anchors.top: parent.top
                anchors.leftMargin: Enums.spacing.l
                anchors.rightMargin: Enums.spacing.l
                anchors.topMargin: control.contentPadding
                spacing: 0
            }
        }
        
    }

    // ==================== Border Overlay 边框层（最上层 + 不在 mainContainer 内）====================
    // 必须在 mainContainer 外, 否则 mainContainer.clip:true 会把贴边 1px 描边裁掉
    Rectangle {
        anchors.fill: mainContainer
        radius: control._radius
        color: Enums.transparent
        border.width: Enums.border.thin
        // borderLight (黑 6%) 在 controlBg (#fefefe) 上几乎不可见, 改用 borderStrong (黑 12%)
        border.color: Enums.stateColor.borderStrong
        z: Enums.zIndex.controlsAbove
    }
}
