// Copyright 2026 aki-riko
// SPDX-License-Identifier: MIT
// This file is part of PrismQML, licensed under MIT.

import QtQuick
import QtQuick.Effects
import "../../.."
import "../Card"
import "../../../effects"
import ".."
import "_internal" as ExpanderInternal

// ExpanderCore - Expander using Card base 展开器基类
Widget {
    id: control
    
    // ==================== Public Props 公开属性 ====================
    property alias title: headerView.title
    property alias content: headerView.content  // Description text 描述文本
    property string icon: ""
    property bool expanded: false
    property bool disabled: false
    // contentArea 上下 padding (左右始终 spacing.l). 引擎统一负责 expandContent 上下间距,
    // 默认 spacing.l (12px) 符合 Microsoft Fluent Design 规范 (WinUI 3 Expander 标准).
    // 业务直接塞 GridLayout / Row / Column 等无自带 padding 容器即可上下对称, 不需要包 Item.
    // 设 0 退回旧行为 (业务自管 padding, 仅在已知内容自带 verticalCenter padding 时使用).
    property int contentPadding: Enums.spacing.l
    property real borderWidth: Enums.surfaceBorderWidth(Enums.border.thin) // Surface border width 表面边线宽度
    property color borderColor: Enums.stateColor.borderStrong // Surface border color 表面边线颜色
    default property alias expandContent: contentArea.data
    
    // Header right content (between title and expand button) 头部右侧内容（标题和展开按钮之间）
    property alias headerContent: headerView.headerContent
    // Hook for subclass to handle widget addition 子类处理控件添加的钩子
    property var onWidgetAdded: null

    // ==================== Readonly State 只读状态 ====================
    readonly property int _radius: Enums.surfaceRadius(Enums.radius.card)
    readonly property bool hovered: headerView.hovered
    readonly property bool pressed: headerView.pressed
    
    // ==================== Signals 信号 ====================
    signal toggled(bool expanded)
    // Note: expandedChanged signal is auto-generated by 'expanded' property 注意：expandedChanged 信号由 expanded 属性自动生成
    
    // ==================== Public Methods 公开方法 ====================
    // Get expanded state 获取展开状态
    function isExpanded() {
        return expanded
    }
    
    
    // Toggle expanded state 切换展开状态
    function toggle() {
        expanded = !expanded
        toggled(expanded)
    }
    
    
    // Expand 展开
    function expand() {
        expanded = true
    }
    
    // Collapse 收起
    function collapse() {
        expanded = false
    }
    
    // Add widget to header (right side) 添加控件到头部（右侧）
    function addHeaderWidget(widget) {
        if (headerView.headerContentLoader
                && headerView.headerContentLoader.item) {
            widget.parent = headerView.headerContentLoader.item
        }
    }
    
    // Add widget to expand content area 添加控件到展开内容区域
    function addExpandWidget(widget) {
        widget.parent = contentArea
        // Call hook if defined (for subclass customization)
        if (typeof onWidgetAdded === "function") {
            onWidgetAdded(widget)
        }
    }
    
    // ==================== Size 尺寸 ====================
    // Content size (inherited from Widget, only width) 内容尺寸（继承自Widget，仅宽度）
    contentWidth: Enums.controlSize.cardWidth
    // Height is always dynamic 高度始终动态
    implicitHeight: mainContainer.height + Enums.spacing.xs
    
    // ==================== Content 内容 ====================
    // Shadow layer 阴影层
    // Fluent: 模糊阴影; Neobrutalism: 硬阴影(NeoShadow)。
    RectangularShadow {
        anchors.fill: mainContainer
        radius: control._radius
        color: Enums.shadow.level2.color
        blur: Enums.shadow.level2.blur
        offset.x: 0
        offset.y: Enums.shadow.level2.offset
        visible: Enums.usesSoftElevation && !Enums.isNeumorphism
    }

    NeumorphicShadow {
        target: mainContainer
        visible: Enums.isNeumorphism
        z: mainContainer.z - 1
    }

    NeoShadow {
        target: mainContainer
        visible: Enums.isNeobrutalism
        radius: control._radius
        z: mainContainer.z - 1
    }
    
    // Main container without border; clips content 主容器无边框，仅裁剪内容
    Item {
        id: mainContainer
        anchors.left: parent.left
        anchors.right: parent.right
        anchors.top: parent.top
        height: headerView.height + (control.expanded ? viewContainer.height : 0)
        clip: true
        opacity: control.disabled ? Enums.opacityLevel.disabled : Enums.opacityLevel.visible
        
        // Height animation 高度动画
        Behavior on height { 
            NumberAnimation { 
                duration: Enums.duration.medium
                easing.type: Easing.OutQuad 
            } 
        }
        
        // Background layer 背景层
        Rectangle {
            id: bgRect
            anchors.fill: parent
            radius: control._radius
            color: Enums.stateColor.controlBg
            // neo: 粗黑边(Fluent 无边靠阴影区分; neo 需黑边)
            border.width: Enums.hasOutlinedSurfaces
                ? control.borderWidth : Enums.border.none
            border.color: Enums.hasOutlinedSurfaces
                ? control.borderColor : Enums.transparent

            TicketPaper {
                anchors.fill: parent
            }
        }
        
        // Header content 头部内容
        ExpanderInternal.HeaderContent {
            id: headerView
            expanderControl: control
        }
        
        // Separator 分隔线
        Separator {
            anchors.top: headerView.bottom
            anchors.left: parent.left
            anchors.right: parent.right
            lineColor: Enums.stateColor.expanderSeparator
            // Content divider remains visible when neumorphic surface outlines are disabled.
            // 内容分隔线独立于表面描边，新拟态仍需保留分隔线。
            lineWidth: Enums.border.thin
            visible: control.expanded
            // 必须高于 viewContainer, 否则 viewContainer 内 expandViewBg
            // (anchors.topMargin: -_radius 向上延伸) 会盖住 separator
            z: 1
        }
        
        // Expanded view 展开内容
        Item {
            id: viewContainer
            anchors.top: headerView.bottom
            anchors.left: parent.left
            anchors.right: parent.right
            // contentPadding 默认 0 (兼容 SettingsCard 内层 Item 自带 padding 场景);
            // 业务装 GridLayout/Row 等无自带 padding 容器时设非 0 让上下对称
            height: control.expanded ? contentArea.implicitHeight + control.contentPadding * 2 : 0
            visible: control.expanded

            // Background with bottom radius 带底部圆角的背景
            Rectangle {
                readonly property int _outlinedInset: Enums.hasOutlinedSurfaces
                    ? Enums.surfaceBorderWidth(Enums.border.thin) : 0

                anchors.fill: parent
                color: Enums.stateColor.expandViewBg
                // Only bottom corners rounded 只有底部圆角
                radius: control._radius
                // Clip top corners by extending above 通过向上延伸裁剪顶部圆角
                anchors.topMargin: -control._radius
                // neo: 左右下各内缩边框宽度, 露出底层 bgRect 的黑边(否则白块贴边盖住黑边,
                // 展开后底部+两侧看不到边)。不加自己的边框, 避免盒中盒。
                anchors.leftMargin: _outlinedInset
                anchors.rightMargin: _outlinedInset
                anchors.bottomMargin: _outlinedInset
            }

            // Content area 内容区域（Column 布局，子控件垂直排列）
            Column {
                id: contentArea
                objectName: "contentArea"
                anchors.left: parent.left
                anchors.right: parent.right
                anchors.top: parent.top
                anchors.leftMargin: Enums.spacing.l
                anchors.rightMargin: Enums.spacing.l
                anchors.topMargin: control.contentPadding
                spacing: Enums.spacing.none
            }
        }
        
    }

    // Border overlay above and outside mainContainer 边框层位于最上层且不在 mainContainer 内
    // 必须在 mainContainer 外, 否则 mainContainer.clip:true 会把贴边 1px 描边裁掉
    Rectangle {
        anchors.fill: mainContainer
        radius: control._radius
        color: Enums.transparent
        border.width: control.borderWidth
        // Standalone expanders default to a strong edge; embedded surfaces may inject their own token.
        // 独立展开器默认使用强边线；嵌入式表面可注入自己的令牌。
        border.color: control.borderColor
        z: Enums.zIndex.controlsAbove
    }
}
